### ISSUE TITLE
French Layout is still there, upon each launch

### ISSUE THREAD

**Issue by DelmorS** [KingDavidW/DarkMessiah-Restoration-Mod-Files#2]
On ModDB I've read, that this mod should fix French layout bug. And it is still there - upon each launch French layout appears in Language selection panel (Win+Space) and is not removable via standard Windows language menus. The only way to remove it either changing something in Registry or copying language parameters via Advanced Language Parameters and rebooting computer.
Windows 11, 23H2

**Comment by rrPKrr** [comment]
Thanks for the heads up. I was eager to install the Restoration Mod primarily because of this particular issue. No way I am installing/launching Dark Messiah of Might and Magic without being 100% sure that this fr keyboard bug is fixed though.

>  The only way to remove it either changing something in Registry or copying language parameters via Advanced Language Parameters and rebooting computer.

The problem is that this fr layout bug is only a tip of an iceberg. If I remember correctly the last time I launched Dark Messiah a few years ago I had to reinstall Windows from scratch to resolve all the related issues. You definitely can remove french layout from the system tray, but the game does something strange to your system. Some broken Windows UI elements will be present in the language related menus even after uninstalling the layout. The system locale becomes some mishmash of English/French languages (ie some installers might be in english but yes/no buttons will be in french, or vice versa). That kind of stuff.

**Comment by DelmorS** [comment]
> Thanks for the heads up. I was eager to install the Restoration Mod primarily because of this particular issue. No way I am installing/launching Dark Messiah of Might and Magic without being 100% sure that this fr keyboard bug is fixed though.
> 
> > The only way to remove it either changing something in Registry or copying language parameters via Advanced Language Parameters and rebooting computer.
> 
> The problem is that this fr layout bug is only a tip of an iceberg. If I remember correctly the last time I launched Dark Messiah a few years ago I had to reinstall Windows from scratch to resolve all the related issues. You definitely can remove french layout from the system tray, but the game does something strange to your system. Some broken Windows UI elements will be present in the language related menus even after uninstalling the layout. The system locale becomes some mishmash of English/French languages (ie some installers might be in english but yes/no buttons will be in french, or vice versa). That kind of stuff.

Wow, it sound terrible. Fortunatelly, I did not meet any of those problems with partial languages here and there in menus. But may it is because I returned back locale by copying parameters via Advanced Language Parameters. May be this bad locale was completely overwritten by this functionality back, and that is why I have no problems.

Anyways, quite sad, that bug is not fixed for us. I played only first two levels of the game, and I really liked it, and paused only because of this bug...

**Comment by rrPKrr** [comment]
I decided to check if it works on Windows 10 22H2. The game installs broken french keyboard there as well. But it seems like Restoration Mod removes it on pc restart. Have you tried simply restarting your computer after launching the game? Just curious if there is any difference between Win10/11.

**Comment by KingDavidW** [comment]
This issue has been resolved and moved to the mod launcher for global launch fixes
